name: Deploy to Apigee

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7.16
      uses: actions/setup-python@v1
      with:
        python-version: 2.7.16
    - name: Deploy to Apigee
      run: |
        python deploy.py -n Car-Data-API -u username:password -o emea-poc13 -e test -p car-data -d .
